---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: auto=true url=http://10.0.1.210:8080/preseed.cfg url/checksum=5d5f84479dec87ceb70d7974b4ef4c32 hostname=mca30 domain=wachterlab.com
